import 'package:maleva/features/planning/models/plan_line.dart';

/// `{...row, field: value}` for [PlanLine]; the row keeps its local identity unless [uid] is given.
extension PlanLineCopy on PlanLine {
  PlanLine copyWith({
    int? uid,
    int? id,
    int? sdId,
    int? planingMasterRefId,
    int? saleOrderMasterRefId,
    String? sortByD,
    String? originalSortByD,
    String? remarks,
    String? truckName,
    int? truckRefid,
    String? truckNameD,
    String? driverName,
    int? driverRefid,
    String? driverNameD,
    String? sPickupDate,
    String? sDeliveryDate,
    String? origin,
    String? destination,
    String? originD,
    String? destinationD,
    String? customerName,
    String? packageType,
    String? vesselName,
    String? jobNo,
    String? picName,
    String? loadingETA,
    String? offloadingETA,
    String? status,
    String? jobStatus,
    String? rtiNo,
    int? rtiMasterRefId,
    String? jobDate,
    String? jobName,
    String? awbNo,
    String? blCopy,
    String? truckSize,
    String? pickupDate,
    String? deliveryDate,
    String? pickupDateD,
    String? deliveryDateD,
    String? sPort,
    String? oPort,
    String? pickuptimelist,
    String? pickupQuantitylist,
    String? deliveryQuantitylist,
    String? delivertimelist,
    String? wareHouseEnterDate,
    String? wareHouseExitDate,
    String? wareHouseAddress,
    String? pickupAddress,
    String? deliveryAddress,
    List<Map<String, dynamic>>? pickupsList,
    List<Map<String, dynamic>>? deliveriesList,
    bool? print,
  }) =>
      PlanLine(
        uid: uid ?? this.uid,
        id: id ?? this.id,
        sdId: sdId ?? this.sdId,
        planingMasterRefId: planingMasterRefId ?? this.planingMasterRefId,
        saleOrderMasterRefId: saleOrderMasterRefId ?? this.saleOrderMasterRefId,
        sortByD: sortByD ?? this.sortByD,
        originalSortByD: originalSortByD ?? this.originalSortByD,
        remarks: remarks ?? this.remarks,
        truckName: truckName ?? this.truckName,
        truckRefid: truckRefid ?? this.truckRefid,
        truckNameD: truckNameD ?? this.truckNameD,
        driverName: driverName ?? this.driverName,
        driverRefid: driverRefid ?? this.driverRefid,
        driverNameD: driverNameD ?? this.driverNameD,
        sPickupDate: sPickupDate ?? this.sPickupDate,
        sDeliveryDate: sDeliveryDate ?? this.sDeliveryDate,
        origin: origin ?? this.origin,
        destination: destination ?? this.destination,
        originD: originD ?? this.originD,
        destinationD: destinationD ?? this.destinationD,
        customerName: customerName ?? this.customerName,
        packageType: packageType ?? this.packageType,
        vesselName: vesselName ?? this.vesselName,
        jobNo: jobNo ?? this.jobNo,
        picName: picName ?? this.picName,
        loadingETA: loadingETA ?? this.loadingETA,
        offloadingETA: offloadingETA ?? this.offloadingETA,
        status: status ?? this.status,
        jobStatus: jobStatus ?? this.jobStatus,
        rtiNo: rtiNo ?? this.rtiNo,
        rtiMasterRefId: rtiMasterRefId ?? this.rtiMasterRefId,
        jobDate: jobDate ?? this.jobDate,
        jobName: jobName ?? this.jobName,
        awbNo: awbNo ?? this.awbNo,
        blCopy: blCopy ?? this.blCopy,
        truckSize: truckSize ?? this.truckSize,
        pickupDate: pickupDate ?? this.pickupDate,
        deliveryDate: deliveryDate ?? this.deliveryDate,
        pickupDateD: pickupDateD ?? this.pickupDateD,
        deliveryDateD: deliveryDateD ?? this.deliveryDateD,
        sPort: sPort ?? this.sPort,
        oPort: oPort ?? this.oPort,
        pickuptimelist: pickuptimelist ?? this.pickuptimelist,
        pickupQuantitylist: pickupQuantitylist ?? this.pickupQuantitylist,
        deliveryQuantitylist: deliveryQuantitylist ?? this.deliveryQuantitylist,
        delivertimelist: delivertimelist ?? this.delivertimelist,
        wareHouseEnterDate: wareHouseEnterDate ?? this.wareHouseEnterDate,
        wareHouseExitDate: wareHouseExitDate ?? this.wareHouseExitDate,
        wareHouseAddress: wareHouseAddress ?? this.wareHouseAddress,
        pickupAddress: pickupAddress ?? this.pickupAddress,
        deliveryAddress: deliveryAddress ?? this.deliveryAddress,
        pickupsList: pickupsList ?? this.pickupsList,
        deliveriesList: deliveriesList ?? this.deliveriesList,
        print: print ?? this.print,
      );
}
