// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9tkh1myRzjGoSQR_JrvB_suDaPOiZOhQ',
    appId: '1:99519924561:web:a89f710373ef9b1ec4ab70',
    messagingSenderId: '99519924561',
    projectId: 'maleva-4eefb',
    authDomain: 'maleva-4eefb.firebaseapp.com',
    storageBucket: 'maleva-4eefb.firebasestorage.app',
    measurementId: 'G-86LH83NTFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3O9i3QjcUTSpCI58RLjRp75I4jV9fwP4',
    appId: '1:99519924561:android:6cc6c0058a19077fc4ab70',
    messagingSenderId: '99519924561',
    projectId: 'maleva-4eefb',
    storageBucket: 'maleva-4eefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeDwL0cG6ncaULc6qAd4Og5ojHMhAo2NI',
    appId: '1:99519924561:ios:7ea348f390613fe5c4ab70',
    messagingSenderId: '99519924561',
    projectId: 'maleva-4eefb',
    storageBucket: 'maleva-4eefb.firebasestorage.app',
    iosBundleId: 'com.kassapos.malevaios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeDwL0cG6ncaULc6qAd4Og5ojHMhAo2NI',
    appId: '1:99519924561:ios:54783eae889e8b7fc4ab70',
    messagingSenderId: '99519924561',
    projectId: 'maleva-4eefb',
    storageBucket: 'maleva-4eefb.firebasestorage.app',
    iosBundleId: 'com.kassapos.malevaios.RunnerTests',
  );
}
